spring.application.name=cricklocal-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cricklocal_db
spring.datasource.username=postgres
spring.datasource.password=YourNewPassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google OAuth
# Google OAuth
spring.security.oauth2.client.registration.google.client-id=428574779124-u5p9n1dkqoiivav7e15s5i6qfopb1db8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE

logging.level.org.springframework.security.oauth2.client.web.HttpSessionOAuth2AuthorizationRequestRepository=TRACE
